name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Run Tests
        run: npm run test
